# -*- coding: utf-8 -*-
"""Stable Diffusion updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSm_hiWBwN_9-ZwbeIoamlKIrpVZJSZf
"""

# Install required packages
!pip install diffusers transformers accelerate torch xformers flask-ngrok pyngrok pillow matplotlib flask_cors

import torch
from diffusers import StableDiffusionImg2ImgPipeline
import PIL
from io import BytesIO
import base64
import matplotlib.pyplot as plt
import numpy as np
from flask import Flask, request, jsonify, render_template_string
from pyngrok import ngrok
import threading
import time
import os

# Set up ngrok for public URL - you need to get your own auth token from https://dashboard.ngrok.com/
!ngrok config add-authtoken 33nn8QHN31Zk1PcZyE6CT3L1l8R_6qLh9raocRX7mXxNTCfC6

class StableDiffusionWebApp:
    def __init__(self):
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.pipe = None
        self.app = Flask(__name__)
        self.setup_routes()
        self.load_model()

    def load_model(self):
        """Load the Stable Diffusion model"""
        print("Loading Stable Diffusion model...")
        self.pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
            "runwayml/stable-diffusion-v1-5",
            torch_dtype=torch.float16,
            use_safetensors=True,
            safety_checker=None,
            requires_safety_checker=False
        )
        self.pipe = self.pipe.to(self.device)

        # Enable optimizations for faster generation
        if self.device == "cuda":
            self.pipe.enable_attention_slicing()
            if hasattr(self.pipe, 'enable_vae_slicing'):
                self.pipe.enable_vae_slicing()
            if hasattr(self.pipe, 'enable_xformers_memory_efficient_attention'):
                try:
                    self.pipe.enable_xformers_memory_efficient_attention()
                    print("XFormers enabled for faster generation")
                except:
                    print("XFormers not available, using default attention")

        print("Model loaded successfully!")

    def resize_image(self, image, max_size=768):
        """Resize image while maintaining aspect ratio"""
        width, height = image.size
        if max(width, height) > max_size:
            if width > height:
                new_width = max_size
                new_height = int(height * max_size / width)
            else:
                new_height = max_size
                new_width = int(width * max_size / height)
            image = image.resize((new_width, new_height), PIL.Image.LANCZOS)
        return image

    def generate_images(self, image, prompt, negative_prompt, strength, guidance_scale, num_images, steps, seed=None):
        """Generate images using Stable Diffusion"""
        # Resize image for faster processing
        image = self.resize_image(image, max_size=512)  # Reduced size for faster generation

        # Set up generator
        if seed:
            generator = torch.Generator(device=self.device).manual_seed(int(seed))
        else:
            generator = None

        # Generate images with optimized settings
        with torch.autocast(device_type='cuda' if self.device == "cuda" else 'cpu'):
            results = self.pipe(
                prompt=prompt,
                image=image,
                strength=strength,
                guidance_scale=guidance_scale,
                negative_prompt=negative_prompt,
                num_inference_steps=steps,
                generator=generator,
                num_images_per_prompt=num_images
            )

        return results.images

    def setup_routes(self):
        """Setup Flask routes with enhanced frontend"""

        # Enhanced HTML template with beautiful UI
        self.html_template = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>AI Image Magic Studio</title>
            <style>
                @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');

                * {
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
                }

                body {
                    font-family: 'Poppins', sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: #333;
                    min-height: 100vh;
                    position: relative;
                    overflow-x: hidden;
                }

                /* Background Video */
                #background-video {
                    position: fixed;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                    object-fit: cover;
                    z-index: -2;
                    opacity: 0.3;
                    filter: brightness(0.7) contrast(1.2);
                }

                /* Animated Gradient Overlay */
                .gradient-overlay {
                    position: fixed;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                    background: linear-gradient(45deg,
                        rgba(102, 126, 234, 0.8) 0%,
                        rgba(118, 75, 162, 0.7) 25%,
                        rgba(255, 138, 0, 0.6) 50%,
                        rgba(255, 0, 128, 0.7) 75%,
                        rgba(0, 255, 255, 0.8) 100%);
                    background-size: 400% 400%;
                    animation: gradientShift 15s ease infinite;
                    z-index: -1;
                    opacity: 0.6;
                }

                @keyframes gradientShift {
                    0% { background-position: 0% 50%; }
                    50% { background-position: 100% 50%; }
                    100% { background-position: 0% 50%; }
                }

                .container {
                    max-width: 1400px;
                    margin: 0 auto;
                    padding: 30px;
                    position: relative;
                    z-index: 1;
                }

                .header {
                    text-align: center;
                    margin-bottom: 40px;
                    background: rgba(255, 255, 255, 0.95);
                    padding: 30px;
                    border-radius: 20px;
                    box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
                    backdrop-filter: blur(10px);
                    border: 1px solid rgba(255, 255, 255, 0.2);
                }

                .header h1 {
                    font-size: 3.5em;
                    background: linear-gradient(135deg, #667eea, #764ba2, #ff8a00);
                    -webkit-background-clip: text;
                    -webkit-text-fill-color: transparent;
                    background-clip: text;
                    margin-bottom: 10px;
                    font-weight: 700;
                }

                .header p {
                    font-size: 1.2em;
                    color: #666;
                    margin-bottom: 20px;
                }

                .main-content {
                    display: grid;
                    grid-template-columns: 1fr 1fr;
                    gap: 40px;
                    margin-bottom: 40px;
                }

                @media (max-width: 1024px) {
                    .main-content {
                        grid-template-columns: 1fr;
                    }
                }

                .form-section, .preview-section {
                    background: rgba(255, 255, 255, 0.95);
                    padding: 40px;
                    border-radius: 20px;
                    box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
                    backdrop-filter: blur(10px);
                    border: 1px solid rgba(255, 255, 255, 0.2);
                }

                .form-group {
                    margin-bottom: 25px;
                }

                .form-group label {
                    display: block;
                    margin-bottom: 8px;
                    font-weight: 600;
                    color: #333;
                    font-size: 1.1em;
                }

                .form-group input,
                .form-group textarea,
                .form-group select {
                    width: 100%;
                    padding: 15px;
                    border: 2px solid #e1e5e9;
                    border-radius: 12px;
                    font-size: 16px;
                    transition: all 0.3s ease;
                    background: rgba(255, 255, 255, 0.9);
                }

                .form-group input:focus,
                .form-group textarea:focus,
                .form-group select:focus {
                    outline: none;
                    border-color: #667eea;
                    box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
                    background: white;
                }

                /* File input styling */
                .file-input-wrapper {
                    position: relative;
                    overflow: hidden;
                    display: inline-block;
                    width: 100%;
                }

                .file-input-wrapper input[type="file"] {
                    position: absolute;
                    left: 0;
                    top: 0;
                    opacity: 0;
                    width: 100%;
                    height: 100%;
                    cursor: pointer;
                }

                .file-input-style {
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    padding: 20px;
                    border: 2px dashed #667eea;
                    border-radius: 12px;
                    background: rgba(102, 126, 234, 0.05);
                    transition: all 0.3s ease;
                    color: #667eea;
                    font-weight: 500;
                }

                .file-input-style:hover {
                    background: rgba(102, 126, 234, 0.1);
                    border-color: #764ba2;
                }

                .file-name {
                    margin-top: 10px;
                    font-size: 14px;
                    color: #333;
                    background: rgba(0, 0, 0, 0.1);
                    padding: 8px 12px;
                    border-radius: 8px;
                    display: inline-block;
                }

                .params-grid {
                    display: grid;
                    grid-template-columns: 1fr 1fr;
                    gap: 20px;
                }

                @media (max-width: 768px) {
                    .params-grid {
                        grid-template-columns: 1fr;
                    }
                }

                .param-info {
                    font-size: 12px;
                    color: #666;
                    margin-top: 5px;
                    font-style: italic;
                }

                .range-display {
                    display: flex;
                    justify-content: space-between;
                    font-size: 12px;
                    color: #666;
                    margin-top: 5px;
                }

                .btn-group {
                    display: flex;
                    gap: 15px;
                    margin-top: 30px;
                }

                .btn {
                    flex: 1;
                    padding: 18px 30px;
                    border: none;
                    border-radius: 12px;
                    font-size: 18px;
                    font-weight: 600;
                    cursor: pointer;
                    transition: all 0.3s ease;
                    text-align: center;
                    text-decoration: none;
                    display: inline-flex;
                    align-items: center;
                    justify-content: center;
                    gap: 10px;
                }

                .btn-primary {
                    background: linear-gradient(135deg, #667eea, #764ba2);
                    color: white;
                    box-shadow: 0 10px 20px rgba(102, 126, 234, 0.3);
                }

                .btn-primary:hover {
                    transform: translateY(-2px);
                    box-shadow: 0 15px 30px rgba(102, 126, 234, 0.4);
                }

                .btn-secondary {
                    background: rgba(255, 255, 255, 0.9);
                    color: #333;
                    border: 2px solid #e1e5e9;
                }

                .btn-secondary:hover {
                    background: white;
                    border-color: #667eea;
                }

                .loading {
                    display: none;
                    text-align: center;
                    padding: 40px;
                    background: rgba(255, 255, 255, 0.95);
                    border-radius: 20px;
                    margin: 20px 0;
                }

                .loading-spinner {
                    width: 60px;
                    height: 60px;
                    border: 6px solid #f3f3f3;
                    border-top: 6px solid #667eea;
                    border-radius: 50%;
                    animation: spin 1s linear infinite;
                    margin: 0 auto 20px;
                }

                @keyframes spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }

                .results-section {
                    background: rgba(255, 255, 255, 0.95);
                    padding: 40px;
                    border-radius: 20px;
                    box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
                    margin-top: 40px;
                    backdrop-filter: blur(10px);
                }

                .image-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                    gap: 30px;
                    margin-top: 30px;
                }

                .image-card {
                    background: white;
                    border-radius: 15px;
                    overflow: hidden;
                    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
                    transition: transform 0.3s ease;
                }

                .image-card:hover {
                    transform: translateY(-5px);
                }

                .image-card img {
                    width: 100%;
                    height: 300px;
                    object-fit: cover;
                }

                .image-card-content {
                    padding: 20px;
                }

                .image-card h3 {
                    margin-bottom: 10px;
                    color: #333;
                }

                .download-btn {
                    width: 100%;
                    padding: 12px;
                    background: linear-gradient(135deg, #667eea, #764ba2);
                    color: white;
                    border: none;
                    border-radius: 8px;
                    cursor: pointer;
                    font-weight: 600;
                    transition: all 0.3s ease;
                }

                .download-btn:hover {
                    transform: translateY(-2px);
                    box-shadow: 0 5px 15px rgba(102, 126, 234, 0.4);
                }

                .feature-badges {
                    display: flex;
                    flex-wrap: wrap;
                    gap: 10px;
                    margin-top: 20px;
                    justify-content: center;
                }

                .badge {
                    background: rgba(102, 126, 234, 0.1);
                    color: #667eea;
                    padding: 8px 16px;
                    border-radius: 20px;
                    font-size: 14px;
                    font-weight: 500;
                    border: 1px solid rgba(102, 126, 234, 0.2);
                }
            </style>
        </head>
        <body>
            <!-- Background Video -->
            <video id="background-video" autoplay muted loop playsinline>
                <source src="https://assets.mixkit.co/videos/preview/mixkit-abstract-background-with-moving-lines-117-large.mp4" type="video/mp4">
                <!-- Fallback video source -->
                <source src="https://assets.mixkit.co/videos/preview/mixkit-geometric-patterns-motion-117-large.mp4" type="video/mp4">
            </video>

            <!-- Animated Gradient Overlay -->
            <div class="gradient-overlay"></div>

            <div class="container">
                <!-- Header -->
                <div class="header">
                    <h1>🎨 AI Image Magic Studio</h1>
                    <p>Transform your images with the power of Artificial Intelligence</p>
                    <div class="feature-badges">
                        <div class="badge">🚀 Fast Generation</div>
                        <div class="badge">🎯 High Accuracy</div>
                        <div class="badge">🖼️ Multiple Outputs</div>
                        <div class="badge">⚡ Real-time Preview</div>
                    </div>
                </div>

                <!-- Main Content -->
                <div class="main-content">
                    <!-- Form Section -->
                    <div class="form-section">
                        <h2 style="margin-bottom: 30px; color: #333;">Create Your Masterpiece</h2>
                        <form id="generateForm" enctype="multipart/form-data">
                            <!-- Image Upload -->
                            <div class="form-group">
                                <label for="image">📸 Upload Your Image</label>
                                <div class="file-input-wrapper">
                                    <div class="file-input-style">
                                        <span>📁 Click to upload image</span>
                                        <input type="file" id="image" name="image" accept="image/*" required
                                               onchange="document.getElementById('fileName').textContent = this.files[0]?.name || 'No file chosen'">
                                    </div>
                                </div>
                                <div id="fileName" class="file-name" style="color: #333; background: rgba(0,0,0,0.1);">No file chosen</div>
                            </div>

                            <!-- Prompt Inputs -->
                            <div class="form-group">
                                <label for="prompt">✨ Creative Prompt</label>
                                <textarea id="prompt" name="prompt" rows="3"
                                          placeholder="Describe what you want to create... Example: 'a fantasy landscape with castles and waterfalls, highly detailed, digital art'">a fantasy landscape with castles and waterfalls, highly detailed, digital art</textarea>
                            </div>

                            <div class="form-group">
                                <label for="negative_prompt">🚫 Negative Prompt</label>
                                <textarea id="negative_prompt" name="negative_prompt" rows="2"
                                          placeholder="What to avoid in the generated image... Example: 'blurry, low quality, distorted, bad anatomy'">blurry, low quality, distorted, bad anatomy</textarea>
                            </div>

                            <!-- Parameters Grid -->
                            <div class="params-grid">
                                <!-- Transformation Strength -->
                                <div class="form-group">
                                    <label for="strength">🎛️ Transformation Strength</label>
                                    <input type="number" id="strength" name="strength" min="0.1" max="0.9" step="0.1" value="0.75">
                                    <div class="param-info">How much to transform the original image</div>
                                    <div class="range-display">
                                        <span>Subtle (0.1)</span>
                                        <span>Strong (0.9)</span>
                                    </div>
                                </div>

                                <!-- Guidance Scale -->
                                <div class="form-group">
                                    <label for="guidance_scale">🎯 Creativity Guidance</label>
                                    <input type="number" id="guidance_scale" name="guidance_scale" min="1" max="20" step="0.5" value="7.5">
                                    <div class="param-info">How closely to follow your prompt</div>
                                    <div class="range-display">
                                        <span>Flexible (1.0)</span>
                                        <span>Strict (20.0)</span>
                                    </div>
                                </div>

                                <!-- Number of Images -->
                                <div class="form-group">
                                    <label for="num_images">🖼️ Number of Images</label>
                                    <input type="number" id="num_images" name="num_images" min="1" max="4" value="2">
                                    <div class="param-info">How many variations to generate</div>
                                    <div class="range-display">
                                        <span>1</span>
                                        <span>4</span>
                                    </div>
                                </div>

                                <!-- Inference Steps -->
                                <div class="form-group">
                                    <label for="steps">⚡ Quality Steps</label>
                                    <input type="number" id="steps" name="steps" min="10" max="100" value="30">
                                    <div class="param-info">More steps = better quality but slower</div>
                                    <div class="range-display">
                                        <span>Fast (10)</span>
                                        <span>Best (100)</span>
                                    </div>
                                </div>
                            </div>

                            <!-- Seed -->
                            <div class="form-group">
                                <label for="seed">🌱 Seed (Optional)</label>
                                <input type="number" id="seed" name="seed" placeholder="Leave empty for random results">
                                <div class="param-info">For reproducible results - same seed = same output</div>
                            </div>

                            <!-- Buttons -->
                            <div class="btn-group">
                                <button type="submit" class="btn btn-primary">
                                    🚀 Generate Magic
                                </button>
                                <button type="button" class="btn btn-secondary" onclick="clearResults()">
                                    🗑️ Clear All
                                </button>
                            </div>
                        </form>
                    </div>

                    <!-- Preview Section -->
                    <div class="preview-section">
                        <h2 style="margin-bottom: 30px; color: #333;">Live Preview</h2>
                        <div id="preview-area" style="text-align: center; padding: 40px; background: rgba(0,0,0,0.05); border-radius: 12px;">
                            <p style="color: #666;">Your generated images will appear here</p>
                        </div>

                        <!-- Loading Indicator -->
                        <div id="loading" class="loading">
                            <div class="loading-spinner"></div>
                            <h3>✨ Creating Your Masterpiece</h3>
                            <p>AI is working its magic... This usually takes 30-60 seconds</p>
                            <p><small>Transforming your image with advanced neural networks</small></p>
                        </div>
                    </div>
                </div>

                <!-- Results Section -->
                <div id="results" class="results-section" style="display: none;">
                    <!-- Results will be dynamically inserted here -->
                </div>
            </div>

            <script>
                // File name display
                document.getElementById('image').addEventListener('change', function(e) {
                    const fileName = this.files[0]?.name || 'No file chosen';
                    document.getElementById('fileName').textContent = fileName;
                });

                // Form submission
                document.getElementById('generateForm').addEventListener('submit', async function(e) {
                    e.preventDefault();

                    const formData = new FormData();
                    const imageFile = document.getElementById('image').files[0];
                    const prompt = document.getElementById('prompt').value;
                    const negative_prompt = document.getElementById('negative_prompt').value;
                    const strength = document.getElementById('strength').value;
                    const guidance_scale = document.getElementById('guidance_scale').value;
                    const num_images = document.getElementById('num_images').value;
                    const steps = document.getElementById('steps').value;
                    const seed = document.getElementById('seed').value;

                    if (!imageFile) {
                        alert('Please upload an image first!');
                        return;
                    }

                    formData.append('image', imageFile);
                    formData.append('prompt', prompt);
                    formData.append('negative_prompt', negative_prompt);
                    formData.append('strength', strength);
                    formData.append('guidance_scale', guidance_scale);
                    formData.append('num_images', num_images);
                    formData.append('steps', steps);
                    formData.append('seed', seed);

                    // Show loading, hide results
                    document.getElementById('loading').style.display = 'block';
                    document.getElementById('results').style.display = 'none';
                    document.getElementById('preview-area').style.display = 'none';

                    try {
                        const response = await fetch('/generate', {
                            method: 'POST',
                            body: formData
                        });

                        const result = await response.json();

                        if (result.success) {
                            displayResults(result);
                        } else {
                            alert('Error: ' + result.error);
                        }
                    } catch (error) {
                        alert('Error: ' + error);
                    } finally {
                        document.getElementById('loading').style.display = 'none';
                        document.getElementById('preview-area').style.display = 'block';
                    }
                });

                function displayResults(result) {
                    const resultsDiv = document.getElementById('results');
                    let html = `
                        <h2 style="text-align: center; margin-bottom: 30px; color: #333;">🎨 Your Generated Masterpieces</h2>
                        <div style="background: rgba(102, 126, 234, 0.1); padding: 20px; border-radius: 12px; margin-bottom: 30px;">
                            <p><strong>✨ Prompt:</strong> ${result.prompt}</p>
                            <p><strong>⚡ Parameters:</strong> Strength: ${result.strength} | Guidance: ${result.guidance_scale} | Steps: ${result.steps}</p>
                        </div>
                    `;

                    html += `<div class="image-grid">`;

                    // Original image
                    html += `
                        <div class="image-card">
                            <img src="data:image/png;base64,${result.original_image}" alt="Original Image">
                            <div class="image-card-content">
                                <h3>Original Image</h3>
                                <button class="download-btn" onclick="downloadImage('${result.original_image}', 'original_image.png')">
                                    📥 Download Original
                                </button>
                            </div>
                        </div>
                    `;

                    // Generated images
                    result.generated_images.forEach((imgData, index) => {
                        html += `
                            <div class="image-card">
                                <img src="data:image/png;base64,${imgData}" alt="Generated Image ${index + 1}">
                                <div class="image-card-content">
                                    <h3>Magic Creation ${index + 1}</h3>
                                    <button class="download-btn" onclick="downloadImage('${imgData}', 'ai_magic_${index + 1}.png')">
                                        📥 Download Magic ${index + 1}
                                    </button>
                                </div>
                            </div>
                        `;
                    });

                    html += `</div>`;

                    resultsDiv.innerHTML = html;
                    resultsDiv.style.display = 'block';

                    // Scroll to results
                    resultsDiv.scrollIntoView({ behavior: 'smooth' });
                }

                function downloadImage(base64Data, filename) {
                    const link = document.createElement('a');
                    link.href = 'data:image/png;base64,' + base64Data;
                    link.download = filename;
                    link.click();
                }

                function clearResults() {
                    document.getElementById('results').style.display = 'none';
                    document.getElementById('image').value = '';
                    document.getElementById('fileName').textContent = 'No file chosen';
                    document.getElementById('preview-area').style.display = 'block';
                }

                // Fallback if video doesn't load
                setTimeout(() => {
                    const video = document.getElementById('background-video');
                    if (video && video.readyState < 3) {
                        video.style.display = 'none';
                    }
                }, 3000);
            </script>
        </body>
        </html>
        """

        @self.app.route('/')
        def home():
            return render_template_string(self.html_template)

        @self.app.route('/generate', methods=['POST'])
        def generate():
            try:
                # Get form data
                prompt = request.form.get('prompt', '')
                negative_prompt = request.form.get('negative_prompt', '')
                strength = float(request.form.get('strength', 0.75))
                guidance_scale = float(request.form.get('guidance_scale', 7.5))
                num_images = int(request.form.get('num_images', 2))
                steps = int(request.form.get('steps', 30))
                seed = request.form.get('seed')

                # Get uploaded image
                if 'image' not in request.files:
                    return jsonify({'success': False, 'error': 'No image uploaded'})

                image_file = request.files['image']
                if image_file.filename == '':
                    return jsonify({'success': False, 'error': 'No image selected'})

                # Open and process image
                image = PIL.Image.open(image_file.stream).convert('RGB')

                # Generate images
                generated_images = self.generate_images(
                    image=image,
                    prompt=prompt,
                    negative_prompt=negative_prompt,
                    strength=strength,
                    guidance_scale=guidance_scale,
                    num_images=num_images,
                    steps=steps,
                    seed=seed
                )

                # Convert images to base64 for web display
                original_buffer = BytesIO()
                image.save(original_buffer, format='PNG')
                original_base64 = base64.b64encode(original_buffer.getvalue()).decode('utf-8')

                generated_base64 = []
                for gen_img in generated_images:
                    buffer = BytesIO()
                    gen_img.save(buffer, format='PNG')
                    generated_base64.append(base64.b64encode(buffer.getvalue()).decode('utf-8'))

                return jsonify({
                    'success': True,
                    'prompt': prompt,
                    'strength': strength,
                    'guidance_scale': guidance_scale,
                    'steps': steps,
                    'original_image': original_base64,
                    'generated_images': generated_base64
                })

            except Exception as e:
                return jsonify({'success': False, 'error': str(e)})

        @self.app.route('/health')
        def health():
            return jsonify({'status': 'healthy', 'device': self.device})

    def run(self, port=5000):
        """Run the Flask app with public ngrok URL"""
        # Start ngrok tunnel
        public_url = ngrok.connect(port).public_url
        print(f"🚀 AI Image Magic Studio is running!")
        print(f"📱 Public URL: {public_url}")
        print(f"🔗 Local URL: http://localhost:{port}")
        print("\n✨ Features:")
        print("   • Beautiful animated background")
        print("   • Enhanced parameter descriptions")
        print("   • Faster image generation")
        print("   • Mobile-friendly design")
        print("   • Real-time preview")

        # Run Flask app
        self.app.run(host='0.0.0.0', port=port)

# Create and run the enhanced web app
def main():
    web_app = StableDiffusionWebApp()
    web_app.run()

# Start the application
if __name__ == "__main__":
    main()

